Add double conversion flags to folly json
rockset/folly pull request #4
Opened 2022-06-09 23:02 UTC by chaoz2

add double conversion flags in folly json

2022-06-09 23:02 UTC, chaoz2 commented
Current dependencies on/for this PR:
* master
  * **PR #4** <a href="https://app.graphite.dev/github/pr/rockset/folly/4" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/rockset/folly/4?utm_source=stack-comment).

2022-06-15 16:54 UTC, chaoz2 commented
Tested with https://github.com/rockset/rs/pull/12908

2022-06-15 19:04 UTC, tudor requested changes

2022-06-15 19:04 UTC, tudor commented on folly/Conv.h
>  toAppend(
This changes a public API in an open-source project. You can't do this. You can add the flags as the last argument with a default value of `NO_FLAGS`, or add another overload of `toAppend` with the old interface. Please upstream this change to `facebook/folly`.

2022-11-21 21:16 UTC, closed without merging